// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/28/2026, 6:23:28 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/islamdzataev/projects/vip-perila-front/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/islamdzataev/projects/vip-perila-front/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/islamdzataev/projects/vip-perila-front/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/islamdzataev/projects/vip-perila-front/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/islamdzataev/projects/vip-perila-front/plugins/**/*.{js,ts,mjs}","/Users/islamdzataev/projects/vip-perila-front/composables/**/*.{js,ts,mjs}","/Users/islamdzataev/projects/vip-perila-front/utils/**/*.{js,ts,mjs}","/Users/islamdzataev/projects/vip-perila-front/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/islamdzataev/projects/vip-perila-front/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/islamdzataev/projects/vip-perila-front/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/islamdzataev/projects/vip-perila-front/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;